import { Schema, model } from "mongoose";
const listSchema = new Schema({
    name:{
        type:String,
        require:true
    },
    description:{
        type:String,
        require:true
    },
    address:{
        type:String,
        require:true
    },
    regularPrice:{
        type:Number,
        require:true
    },
    discountPrice:{
        type:Number,
        require:true
    },
    bathrooms:{
        type:Number,
        require:true
    },
    bedrooms:{
        type:Number,
        require:true
    },
    furnished:{
        type:Boolean,
        require:true
    },
    parking:{
        type:Boolean,
        require:true
    },
    type:{
        type:String,
        require:true,
        enum:["sale","rent"]
    },
    offer:{
        type:Boolean,
        require:true
    },
    imageURLs:[{
        type:String,
        require:true
    }],
    userRef:{
        type:Schema.Types.ObjectId,
        ref:"User"
    }
},{timestamps:true});
const List = model('List',listSchema);
export default List;