const mongoose = require("mongoose");
const listSchema = new mongoose.Schema({
    name:{
        type:String,
        require:true
    },
    descriptin:{
        type:String,
        require:true
    },
    address:{
        type:String,
        require:true
    },
    regularPrice:{
        type:Number,
        require:true
    },
    discountPrice:{
        type:Number,
        require:true
    },
    bathrooms:{
        type:Number,
        require:true
    },
    bedrooms:{
        type:Number,
        require:true
    },
    furnished:{
        type:Boolean,
        require:true
    },
    parking:{
        type:Boolean,
        require:true
    },
    type:{
        type:String,
        require:true,
        enum:["sale","rent"]
    },
    offer:{
        type:Boolean,
        require:true
    },
    imageURLs:[{
        type:String,
        require:true
    }],
    userRef:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    }
},{timestamps:true});
const List = mongoose.model('List',listSchema);
module.exports = List;